name: Build Spring Boot Application

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생하면 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'       # Java 17 버전 설정
          distribution: 'temurin'  # JDK 제공 배포판 설정

      # 3. Gradle 빌드 (테스트 코드 실행 없이)
      - name: Build with Gradle
        run: ./gradlew build -x test  # 테스트 코드 실행 제외
