name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생하면 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드 (테스트 코드 실행 제외)
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 4. EC2로 빌드 파일 전송 및 배포
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}        # EC2 인스턴스의 퍼블릭 IP
          EC2_USER: "ec2-user"         # EC2 사용자명 (예: ec2-user)
          APP_DIR: "/home/ec2-user"         # EC2에서 앱을 배포할 디렉토리 (예: /home/ec2-user/app)
        run: |
          # SSH 설정
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # EC2에 빌드 파일 전송
          scp -o StrictHostKeyChecking=no build/libs/carrot-moa-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:$APP_DIR/app.jar

          # EC2에서 애플리케이션 실행
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # 현재 실행 중인 애플리케이션 중지 (예: 기존 프로세스 종료)
            pkill -f 'app.jar' || true

            # 애플리케이션 실행
            nohup java -Djasypt.encryptor.password=carrotsS3 -jar /home/ec2-user/app.jar &
